
package view;

import controller.IncluirDAOProduto;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ModelClientes;
import model.ModelProdutos;

public class ViewProdutos extends javax.swing.JFrame {
IncluirDAOProduto DAOP;
ModelProdutos objpro = new ModelProdutos();

    /**
     * Creates new form ViewProdutos
     */
    public ViewProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtproduto = new javax.swing.JTextField();
        jtdescricao = new javax.swing.JTextField();
        jtpreco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        setAlwaysOnTop(true);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 200, 120, 40);

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Cancelar");
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 200, 130, 40);
        getContentPane().add(jtproduto);
        jtproduto.setBounds(70, 119, 180, 41);
        getContentPane().add(jtdescricao);
        jtdescricao.setBounds(280, 120, 310, 41);
        getContentPane().add(jtpreco);
        jtpreco.setBounds(70, 200, 181, 41);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Produto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 90, 110, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Preço");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 174, 80, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Descrição");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 90, 90, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 460);

        setSize(new java.awt.Dimension(653, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
     objpro = new ModelProdutos();
       
     objpro.setProduto(jtproduto.getText());
     objpro.setPreco(Integer.parseInt(jtpreco.getText().trim()));
     objpro.setDescricao(jtdescricao.getText());
     
     DAOP = new IncluirDAOProduto();
    try {
        if(DAOP.Incluir(objpro)){
            JOptionPane.showMessageDialog(this,"Registro salvo com sucesso!");
         apossalvar();
        }        
        
// TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(ViewProdutos.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtdescricao;
    private javax.swing.JTextField jtpreco;
    private javax.swing.JTextField jtproduto;
    // End of variables declaration//GEN-END:variables

public void novo(){
        jtproduto.setText("");
        jtdescricao.setText("");
        jtpreco.setText("");    
        
        jtproduto.setEnabled(true);
        jtdescricao.setEnabled(true);
        jtpreco.setEnabled(false);
       objpro = new ModelProdutos();
}

public void apossalvar(){
        jtproduto.setText("");
        jtdescricao.setText("");
        jtpreco.setText("");    
        
        jtproduto.setEnabled(false);
        jtdescricao.setEnabled(false);
        jtpreco.setEnabled(true);
       objpro = new ModelProdutos();

}

}
